version: '3.7'

services:
  data-generator:
    build: ./data-generator
    environment:
      - MONGO_HOST=db
    depends_on:
      - mongo

  mongo:
    container_name: db
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

volumes:
  mongo:
